inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - 'db/schema.rb'

Style/RaiseArgs:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
