inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - 'db/schema.rb'
    - 'config.ru'
    - 'bin/*'
    - 'config/*'
    - 'lib/tasks/analysis.rake'         ## TODO: anlysis.rake refactor

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'


Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

## intentional
Lint/Void:
  Exclude:
    - 'app/parsers/competition_parser/isu_generic.rb'

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false
#  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
  
Style/RaiseArgs:
  Enabled: false

Style/RegexpLiteral:   # %r{} or //
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator:
    Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
  

Style/UnlessElse:
  Enabled: false

Style/WordArray:
  Exclude: false
  
################
## further check
Style/GuardClause:
  Exclude:
    - 'app/datatables/elements_datatable.rb'
    - 'app/parsers/competition_parser/isu_generic/score_parser.rb'
    - 'lib/ajax_datatables/columns.rb'
    - 'lib/property.rb'

Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/models/component_judge_detail.rb'
    - 'app/models/deviation.rb'
    - 'app/models/element_judge_detail.rb'
    - 'config/initializers/refinements/as_ranking.rb'
    - 'config/initializers/refinements/as_score.rb'
    - 'lib/ajax_datatables/datatable/serversidable.rb'

Style/OptionalArguments:
  Exclude:
    - 'app/helpers/link_to_helper.rb'

## a, b, c = 1, 2, 3
Style/ParallelAssignment:
  Exclude:
    - 'app/controllers/competitions_controller.rb'
    - 'app/parsers/competition_parser/isu_generic/score_parser.rb'
    - 'app/parsers/competition_parser/isu_generic/summary_parser.rb'
    
Style/RedundantSelf:
  Exclude:
    - 'app/models/category_result.rb'
    - 'app/models/competition.rb'
    - 'app/models/component_judge_detail.rb'
    - 'app/models/deviation.rb'
    - 'app/models/element_judge_detail.rb'
    - 'app/models/score.rb'
    - 'lib/ajax_datatables/datatable.rb'
    - 'lib/ajax_datatables/datatable/decoratable.rb'
    - 'lib/ajax_datatables/datatable/defer_loadable.rb'
    - 'lib/ajax_datatables/datatable/limitable.rb'
    - 'lib/ajax_datatables/datatable/serversidable.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'app/models/competition.rb'
    - 'app/models/score.rb'
    - 'app/parsers/competition_parser/isu_generic/score_parser.rb'
    - 'lib/tasks/parse.rake'

# scope, -> to be replaced with lambda ??
Style/Lambda:
  Exclude:
   - 'app/models/skater.rb'

  
Security/Open:
  Exclude:
    - 'app/parsers/competition_parser/isu_generic/score_parser.rb'
    - 'app/parsers/parser.rb'
