inherit_from: .rubocop_todo.yml
#require:
#  - rubocop-rails
#  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - gps_combination.rb

################
Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/RedundantCopEnableDirective:
  Enabled: false

################
Metrics/ClassLength:
  Max: 100
  Exclude:
    - app/updaters/competition_updater.rb       ## TODO
    - app/parsers/competition_parser.rb       ## TODO

Metrics/BlockLength:
  Max: 35
  Exclude:
    - spec/**/*.rb
    - config/routes.rb
    - lib/tasks/**/*.rake

Metrics/MethodLength:
  Max: 40
  Exclude:
    - db/migrate/*.rb

################
## Style
Style/BlockComments:      # allow =begin, =end
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

#Style/Lambda:
#  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/NumericLiterals:     ## 12_345
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:   # %r{} or //
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator:
    Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/WordArray:
  Exclude: false

Style/HashEachMethods:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformKeys:
  Enabled: true

# For rubocop < 1.0.0
Style/HashTransformValues:
  Enabled: true
