language: ruby

rvm:
  - 2.2.10
  - 2.4.1

install: bundle install --deployment

cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
  - bundle exec rspec --tag updater -fd
  - bundle exec rspec --tag feature -fd
  - bundle exec rspec --tag rake -fd
  - bundle exec rspec --tag parser -fd
  - bundle exec rspec --tag error_handler -fd

env:
  TEST: true
  JAVASCRIPT_DRIVER: poltergeist

branches:
  only:
    - master
    - develop
    - /^release/

################
## addon packages

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - poppler-utils
  #chrome: stable

before_install:
  sudo pip install codecov

#before_install:
#  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
#  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
#  - unzip ~/chromedriver_linux64.zip -d ~/
#  - rm ~/chromedriver_linux64.zip
#  - sudo mv -f ~/chromedriver /usr/local/share/
#  - sudo chmod +x /usr/local/share/chromedriver
#  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver  

#before_script:
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3
  
after_success:
  - codecov        
