language: ruby

rvm:
  # - 2.2.10   ## capybara 3.8 requires >= 2.3.0
  - 2.4
  - 2.5

install: bundle install --deployment
cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
  - bundle exec rspec --tag updater -fd
  - bundle exec rspec --tag feature -fd
  - bundle exec rspec --tag rake -fd
  - bundle exec rspec --tag parser -fd
  - bundle exec rspec --tag error_handler -fd

env: TEST=true

branches:
  only:
    - master
    - develop
    - /^release/

sudo: required

dist: trusty
addons:
  apt:
    packages:
      - poppler-utils
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

after_success:
  - codecov        
