language: ruby

rvm:
  - 2.2.5

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rspec --tag updater

env: TEST=true

addons:
  apt:
    packages:
      - poppler-utils

after_success:
  - codecov        