language: ruby

rvm:
  - 2.2.5

install: bundle install --deployment
cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rspec --tag updater
  - bundle exec rspec --tag error_handler
  - bundle exec rspec --tag rake

env: TEST=true

#branches:
#  only:
#    - master
#    - develop
#    - /^release/

addons:
  apt:
    packages:
      - poppler-utils
      - gnuplot

after_success:
  - codecov        
