language: ruby

rvm:
  - 2.2.5
  - 2.4.0

install: bundle install --deployment
cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
  - bundle exec rspec --tag updater -fd
  - bundle exec rspec --tag error_handler -fd
#  - bundle exec rspec --tag rake
#  - bundle exec rspec --tag parser

env: TEST=true

#branches:
#  only:
#    - master
#    - develop
#    - /^release/

addons:
  apt:
    packages:
      - poppler-utils
      - gnuplot

after_success:
  - codecov        
