language: ruby

rvm:
  - 2.2.5

install: bundle install --deployment
cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rspec --tag updater  # error-handler

env: TEST=true

branches:
  only:
    - master
    - develop

addons:
  apt:
    packages:
      - poppler-utils
      - gnuplot

after_success:
  - codecov        