language: ruby

rvm:
  # - 2.2.10   ## capybara 3.8 requires >= 2.3.0
  - 2.4
  - 2.5

install: bundle install --deployment
cache:
  directories: vendor/bundle
  
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec -fd
  - bundle exec rspec --tag updater -fd
  - bundle exec rspec --tag feature -fd
  - bundle exec rspec --tag rake -fd
  - bundle exec rspec --tag parser -fd
  - bundle exec rspec --tag error_handler -fd

env: TEST=true

branches:
  only:
    - master
    - develop
    - /^release/

sudo: required

dist: trusty
addons:
  apt:
    packages:
      - poppler-utils
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver  

env: DISPLAY=:99.0

before_script:
  - sh -e /etc/init.d/xvfb start
  #- wget http://chromedriver.storage.googleapis.com/2.9/chromedriver_linux64.zip
  #- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  #- export CHROME_BIN=chromium-browse
  
after_success:
  - codecov        
