language: ruby
os: linux

rvm:
  - 2.4.4
  - 2.5.1
  # - ruby-head

jobs:
  allow_failures:
    - rvm: ruby-head

install: bundle install --deployment

cache:
  directories: vendor/bundle

script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
  - bundle exec rspec --tag feature
  - bundle exec rspec --tag updater
  - bundle exec rspec --tag rake
  - bundle exec rspec --tag error_handler

env:
  TEST: true
  JS_DRIVER: poltergeist

branches:
  only:
    - master
    - develop
    - /^release/
    - refactoring

################
## addon packages

sudo: required

dist: trusty

addons:
  apt:
    packages:
      - poppler-utils
  #chrome: stable

before_install:
  - pip install codecov
  - gem update --system

after_success:
  - codecov
