- city: Espoo
  country: FIN
  tz: Helsinki
- city: Warsaw
  country: POL
  tz: Warsaw
- city: Saransk
  country: RUS
  tz: Europe/Moscow
- city: Moscow
  country: RUS
  tz: Europe/Moscow
- city: Bratislava
  country:  SVK
  tz: Bratislava
- city: Oberstdorf
  country: GER
- city: 'Bergamo (BG)'
  country: ITA
- city: Vantaa
  country:  SWE
- city: Sesto San Giovanni (MI)
  country:  ITA
