- city: Espoo
  country: FIN
- city: Warsaw
  country: POL
- city: Saransk
  country: RUS
- city: Moscow
  country: RUS
- city: Bratislava
  country:  SVK
- city: Oberstdorf
  country: GER
- city: 'Bergamo (BG)'
  country: ITA
- city: 'Bergamo'
  country: ITA
- city: Vantaa
  country:  SWE
- city: Sesto San Giovanni (MI)
  country:  ITA
