# add any competitions that you want to add into the database.
# if the result site conform to ISU standards format, just add set of short_name and url, i.e:
#  WC2017: http://www.isuresults.com/results/season1617/wc2017/
#
# if it requires specific parser_type, add it with parser_type key as hash e.g.
#  GPF2017:
#    name: ISU Grand Prix of Figure Skating Final 2017
#    site_url: http://www.isuresults.com/results/season1718/gpf1718/
#    parser_type: gpjpn
#    city: Nagoya#
#
#  in that case you need to register the parser_type into:
#    CompetitionParser::Extension::Gpjpn

## olders
GPJPN2006: http://www.isuresults.com/results/gpjpn06/
GPF2006: http://www.isuresults.com/results/gpf0607/
WC2007: http://www.isuresults.com/results/wc2007/
GPJPN07: http://www.isuresults.com/results/gpjpn07/
GPF0708: http://www.isuresults.com/results/gpf0708/
FCC2008: http://www.isuresults.com/results/fc2008/
WC2008: http://www.isuresults.com/results/wc2008/
GPFRA2008: http://www.isuresults.com/results/gpfra08/
GPJPN2008: http://www.isuresults.com/results/gpjpn08/
GPF2008: http://www.isuresults.com/results/gpf0809/
WC2009: http://www.isuresults.com/results/wc2009/
WTT2009: http://www.isuresults.com/results/wtt2009/
FCC2009: http://www.isuresults.com/results/fc2009/
GPFRA2009: http://www.isuresults.com/results/gpfra09/
GPRUS2009: http://www.isuresults.com/results/gprus09/
FCC2010: http://www.isuresults.com/results/fc2010/
OWG2010: http://www.isuresults.com/results/owg2010/
WC2010: http://www.isuresults.com/results/wc2010/

## 2010-11
GPUSA2010: http://www.isuresults.com/results/gpusa2010/
GPCAN2010: http://www.isuresults.com/results/gpcan2010/
GPCHN2010: http://www.isuresults.com/results/gpchn2010/
GPFRA2010: http://www.isuresults.com/results/gpfra2010/
GPRUS2010: http://www.isuresults.com/results/gprus2010/
GPJPN2010: http://www.isuresults.com/results/gpjpn2010/
GPF2010: http://www.isuresults.com/results/gpf1011/
EC2011: http://www.isuresults.com/results/ec2011/
FC2011: http://www.isuresults.com/results/fc2011/
WC2011: http://www.isuresults.com/results/wc2011/

## 2011-12
GPUSA2011: http://www.isuresults.com/results/gpusa2011/
GPCAN2011: http://www.isuresults.com/results/gpcan2011/
GPCHN2011: http://www.isuresults.com/results/gpchn2011/
GPFRA2011: http://www.isuresults.com/results/gpfra2011/
GPRUS2011: http://www.isuresults.com/results/gprus2011/
GPJPN2011: http://www.isuresults.com/results/gpjpn2011/
GPF2011: http://www.isuresults.com/results/gpf1112/
EC2012: http://www.isuresults.com/results/ec2012/
FC2012: http://www.isuresults.com/results/fc2012/
WC2012: http://www.isuresults.com/results/wc2012/
WTT2012: http://www.isuresults.com/results/wtt2012/

## 2012-13
GPUSA2012: http://www.isuresults.com/results/gpusa2012/
GPCAN2012: http://www.isuresults.com/results/gpcan2012/
GPCHN2012: http://www.isuresults.com/results/gpchn2012/
GPFRA2012: http://www.isuresults.com/results/gpfra2012/
GPRUS2012: http://www.isuresults.com/results/gprus2012/
GPJPN2012: http://www.isuresults.com/results/gpjpn2012/
GPF2012: http://www.isuresults.com/results/gpf1213/
FC2013: http://www.isuresults.com/results/fc2013/
EC2013: http://www.isuresults.com/results/ec2013/
WC2013: http://www.isuresults.com/results/wc2013/

## 2013-14
GPUSA2013: http://www.isuresults.com/results/gpusa2013/
GPCAN2013: http://www.isuresults.com/results/gpcan2013/
GPCHN2013: http://www.isuresults.com/results/gpchn2013/
GPFRA2013: http://www.isuresults.com/results/gpfra2013/
GPRUS2013: http://www.isuresults.com/results/gprus2013/
GPJPN2013: http://www.isuresults.com/results/gpjpn2013/
GPF2013: http://www.isuresults.com/results/gpf1314/
FC2014: http://www.isuresults.com/results/fc2014/
EC2014: http://www.isuresults.com/results/ec2014/
WC2014: http://www.isuresults.com/results/wc2014/
OWG2014: http://www.isuresults.com/results/owg2014/

## 2014-15
GPUSA2014: http://www.isuresults.com/results/gpusa2014/
GPCAN2014: http://www.isuresults.com/results/gpcan2014/
GPCHN2014: http://www.isuresults.com/results/gpchn2014/
GPFRA2014: http://www.isuresults.com/results/gpfra2014/
GPRUS2014: http://www.isuresults.com/results/gprus2014/
GPJPN2014: http://www.isuresults.com/results/gpjpn2014/
GPF1415: http://www.isuresults.com/results/gpf1415/
FC2015: http://www.isuresults.com/results/fc2015/
EC2015: http://www.isuresults.com/results/ec2015/
WC2015: http://www.isuresults.com/results/wc2015/

##2015-16
GPUSA2015: http://www.isuresults.com/results/season1516/gpusa2015/
GPCAN2015: http://www.isuresults.com/results/season1516/gpcan2015/
GPCHN2015: http://www.isuresults.com/results/season1516/gpchn2015/
GPFRA2015:
  site_url: http://www.isuresults.com/results/season1516/gpfra2015/
  comment: "Free Skating has been canceled due to explusion in Paris. refere: http://static.isu.org/media/1012/1980-isu-gp-fra-2015-partial-cancelation-info-to-members-public.pdf"

GPRUS2015: http://www.isuresults.com/results/season1516/gprus2015/
GPJPN2015: http://www.isuresults.com/results/season1516/gpjpn2015/
GPF2015: http://www.isuresults.com/results/season1516/gpf1516/
FCC2016: http://www.isuresults.com/results/season1516/fc2016/
EC2016: http://www.isuresults.com/results/season1516/ec2016/
WC2016: http://www.isuresults.com/results/season1516/wc2016/

##2016-17
GPUSA2016: http://www.isuresults.com/results/season1617/gpusa2016/
GPCAN2016: http://www.isuresults.com/results/season1617/gpcan2016/
GPCHN2016: http://www.isuresults.com/results/season1617/gpchn2016/
GPFRA2016: http://www.isuresults.com/results/season1617/gpfra2016  ## /SEG007.HTM  ## live results somehow
GPRUS2016: http://www.isuresults.com/results/season1617/gprus2016/
GPJPN2016: http://www.isuresults.com/results/season1617/gpjpn2016/
GPF2016: http://www.isuresults.com/results/season1617/gpf1617/
FCC2017: http://www.isuresults.com/results/season1617/fc2017/
EC2017: http://www.isuresults.com/results/season1617/ec2017/
WC2017: http://www.isuresults.com/results/season1617/wc2017/
WTT2017:
  site_url: https://www.jsfresults.com/intl/2016-2017/wtt/
  parser_type: :wtt2017
  comment: "no category results provided"

## 2017-18
GPRUS2017: http://www.isuresults.com/results/season1718/gprus2017/
GPCAN2017: http://www.isuresults.com/results/season1718/gpcan2017/
GPCHN2017: http://www.isuresults.com/results/season1718/gpchn2017/
GPJPN2017:
  site_url: http://www.isuresults.com/results/season1718/gpjpn2017/
  parser_type: gpjpn
  name: ISU GP NHK Trophy 2017
  city: Osaka
GPFRA2017: http://www.isuresults.com/results/season1718/gpfra2017/
GPUSA2017: http://www.isuresults.com/results/season1718/gpusa2017/
GPF2017:
  name: ISU Grand Prix of Figure Skating Final 2017
  site_url: http://www.isuresults.com/results/season1718/gpf1718/
  parser_type: gpjpn
  city: Nagoya
OWG2018: http://www.isuresults.com/results/season1718/owg2018/
EC2018: http://www.isuresults.com/results/season1718/ec2018/
WC2018: http://www.isuresults.com/results/season1718/wc2018/
FCC2018: http://www.isuresults.com/results/season1718/fc2018/


## 2018-19
GPUSA2018: http://www.isuresults.com/results/season1819/gpusa2018/
GPCAN2018:
  site_url: http://www.isuresults.com/results/season1819/gpcan2018/
  encoding: iso-8859-1
GPFIN2018: http://www.isuresults.com/results/season1819/gpfin2018/
GPFRA2018: http://www.isuresults.com/results/season1819/gpfra2018/
GPRUS2018: http://www.isuresults.com/results/season1819/gprus2018/
GPJPN2018:
  site_url: http://www.isuresults.com/results/season1819/gpjpn2018/
  parser_type: gpjpn
  name: ISU GP NHK Trophy 2018
  city: Hiroshima
GPF2018: http://www.isuresults.com/results/season1819/gpf1819/
WC2019:
  name: ISU World Figureskating Championships 2019
  site_url: http://www.isuresults.com/results/season1819/wc2019/
  parser_type: gpjpn
  city: Saitama
FCC2019: http://www.isuresults.com/results/season1819/fc2019/
EC2019:
  site_url: http://www.isuresults.com/results/season1819/ec2019/
  encoding: iso-8859-1
#CSFIN2014: http://www.figureskatingresults.fi/results/1415/CSFIN2014/
#DEBUG: http://www.kraso.sk/wp-content/uploads/sutaze/2014_2015/20141001_ont/html/
WTT2017:
  site_url: https://www.jsfresults.com/intl/2016-2017/wtt/
  parser_type: :wtt2017
  comment: "no category results provided"

## 2019-20
GPJPN2019:
  site_url: http://www.isuresults.com/results/season1920/gpjpn2019/
  parser_type: gpjpn2019
  name: ISU GP NHK Trophy 2019
  city: Tokyo
GPUSA2019: http://www.isuresults.com/results/season1920/gpusa2019/
GPCAN2019:
  site_url: http://www.isuresults.com/results/season1920/gpcan2019/
  encoding: iso-8859-1
GPCHN2019: http://www.isuresults.com/results/season1920/gpchn2019/
GPFRA2019: http://www.isuresults.com/results/season1920/gpfra2019/
GPRUS2019: http://www.isuresults.com/results/season1920/gprus2019/
GPF2019: http://www.isuresults.com/results/season1920/gpf1920/
