"Grand Prix .*Final": ["isu", "gp", "GPF%{year}"]
"^ISU GP.*Final": ["isu", "gp", "GPF%{year}"]
"^ISU GP":  ["isu", "gp", "GP%{country}%{year}"]
"Olympic":  ["isu", "olympic", "OWG%{year}", "Olympic Winter Games %{city} %{year}"]
"^ISU World Figure": ["isu", "world", "WORLD%{year}", "ISU World Championships %{year}"]
"^ISU World Championships": ["isu", "world", "WORLD%{year}", "ISU World Championships %{year}"]
"^ISU Four Continents": ["isu", "fcc", "FCC%{year}", "ISU Four Continents Championships %{year}"]
"^ISU European": ["isu", "euro", "EURO%{year}", "ISU European Championships %{year}"]
"^ISU World Team": ["isu", "team", "TEAM%{year}", "ISU World Team Trophy %{year}"]
"^ISU World Junior": ["isu", "jworld", "JWORLD%{year}"]
"^ISU Junior Grand Prix": ["isu", "jgp", "JGP%{country}%{year}"]
"^Finlandia Trophy": ["challenger", "finlandia", "FINLANDIA%{year}", "Finlandia Trophy %{year}"]
"Warsaw Cup": ["challenger", "warshaw", "WARSAW%{year}", "Warsaw Cup %{year}"]
"Autumn Classic": ["challenger", "aci", "ACI%{year}"]
"Nebelhorn": [ "challenger", "nebelhorn", "NEBELHORN%{year}", "Nebelhorn Trophy %{year}"]
"Lombardia":  ["challenger", "lombaridia", "LOMBARDIA%{year}", "Lombardia Trophy %{year}"]
"Ondrej Nepela": ["challenger", "nepela", "NEPELA%{year}", "Ondrej Nepela Trophy %{year}"]


