#-
#  site_url: https://www.jsfresults.com/National/2004-2005/Figure/AllJapan/J/
#  parser_type: all_japan
#  encoding: Shift_JIS

#-
#  site_url: https://www.jsfresults.com/National/2005-2006/Figure/national/J/
#  parser_type: all_japan
#  encoding: Shift_JIS

AJ2006:
  site_url: https://www.jsfresults.com/National/2006-2007/Figure/national/J/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2007:
  site_url: https://www.jsfresults.com/National/2007-2008/fs/national/J/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2008:
  site_url: https://www.jsfresults.com/National/2008-2009/fs/national/J/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2009:
  site_url: https://www.jsfresults.com/National/2009-2010/fs/national/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2010:
  site_url: https://www.jsfresults.com/National/2010-2011/fs/national/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2011:
  site_url: https://www.jsfresults.com/National/2011-2012/fs_j/national/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2012:
  site_url: https://www.jsfresults.com/National/2012-2013/fs_j/national/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2013:
  site_url: https://www.jsfresults.com/National/2013-2014/fs_j/nationals/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2014:
  site_url: https://www.jsfresults.com/National/2014-2015/fs_j/national/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2015:
  site_url: https://www.jsfresults.com/National/2015-2016/fs_j/nationalsenior/
  parser_type: all_japan
  encoding: Shift_JIS
AJ2016:
  site_url: https://www.jsfresults.com/National/2016-2017/fs_j/nationalsenior/
  parser_type: all_japan
AJ2017:
  site_url: https://www.jsfresults.com/National/2017-2018/fs_j/nationalsenior/
  parser_type: all_japan

## debug
