# add any competitions that you want to add into the database.
# if the result site conform to ISU standards format, just add the url as array.
# if it requires specific parser, add it with parser key as hash e.g.
#   -
#     url: http://www.foo.bar/results/xxxx2017/
#     parser: foo
#
#  in that case you need to register the parser into Fisk8Viewer::CompetitionSummaryParser.registered. see fisk8viewer/competition_summary_parser.rb and fisk8viewer/competition_summary_parser/isu_generic.rb for dettails.

##2010-11
-
  url: http://www.isuresults.com/results/gpusa2010/
  parser: :isu_generic_mdy
-
  url: http://www.isuresults.com/results/gpcan2010/
  parser: :isu_generic_mdy
- http://www.isuresults.com/results/gpchn2010/
-
  url: http://www.isuresults.com/results/gpfra2010/
  parser: :isu_generic_mdy
- http://www.isuresults.com/results/gprus2010/
- http://www.isuresults.com/results/gpjpn2010/
- http://www.isuresults.com/results/gpf1011/
-
  url: http://www.isuresults.com/results/ec2011/
  parser: :isu_generic_mdy
- http://www.isuresults.com/results/fc2011/
- http://www.isuresults.com/results/wjc2011/
- http://www.isuresults.com/results/wc2011/
- http://www.isuresults.com/results/owg2010/

-
  url: http://www.isuresults.com/results/jgpfra2010/
  parser: :isu_generic_mdy

- http://www.isuresults.com/results/jgprou2010/
-
  url: http://www.isuresults.com/results/jgpaut2010/
  parser: :isu_generic_mdy
  
- http://www.isuresults.com/results/jgpjpn2010/
-
  url: http://www.isuresults.com/results/jgpgbr2010/
  parser: :isu_generic_mdy
  
- http://www.isuresults.com/results/jgpger2010/
-
  url: http://www.isuresults.com/results/jgpcze2010/
  parser: :isu_generic_mdy


##2011-12
- http://www.isuresults.com/results/gpusa2011/
- http://www.isuresults.com/results/gpcan2011/
- http://www.isuresults.com/results/gpchn2011/
- http://www.isuresults.com/results/gpfra2011/
- http://www.isuresults.com/results/gprus2011/
- http://www.isuresults.com/results/gpjpn2011/
- http://www.isuresults.com/results/gpf1112/
-
  url: http://www.isuresults.com/results/ec2012/
  parser: :isu_generic_mdy
-
  url: http://www.isuresults.com/results/fc2012/
  parser: :isu_generic_mdy
-
  url: http://www.isuresults.com/results/wjc2012/
  parser: :isu_generic_mdy
- http://www.isuresults.com/results/wc2012/
- http://www.isuresults.com/results/wtt2012/

- http://www.isuresults.com/results/jgplat2011/
- http://www.isuresults.com/results/jgpaus2011/
- http://www.isuresults.com/results/jgppol2011/
- http://www.isuresults.com/results/jgprou2011/
- http://www.isuresults.com/results/jgpaut2011/
- http://www.isuresults.com/results/jgpita2011/
- http://www.isuresults.com/results/jgpest2011/

##2012-3
- http://www.isuresults.com/results/gpusa2012/
- http://www.isuresults.com/results/gpcan2012/
- http://www.isuresults.com/results/gpchn2012/
- http://www.isuresults.com/results/gpfra2012/
- http://www.isuresults.com/results/gprus2012/
- http://www.isuresults.com/results/gpjpn2012/
- http://www.isuresults.com/results/gpf1213/
- http://www.isuresults.com/results/fc2013/
-
  url: http://www.isuresults.com/results/ec2013/
  parser: :isu_generic_mdy
- http://www.isuresults.com/results/wjc2013/
- http://www.isuresults.com/results/wc2013/

- http://www.isuresults.com/results/jgpfra2012/
- http://www.isuresults.com/results/jgpusa2012/
- http://www.isuresults.com/results/jgpaut2012/
- http://www.isuresults.com/results/jgptur2012/
- http://www.isuresults.com/results/jgpslo2012/
- http://www.isuresults.com/results/jgpcro2012/
- http://www.isuresults.com/results/jgpger2012/

##2013-4
- http://www.isuresults.com/results/gpusa2013/
- http://www.isuresults.com/results/gpcan2013/
- http://www.isuresults.com/results/gpchn2013/
- http://www.isuresults.com/results/gpfra2013/
- http://www.isuresults.com/results/gprus2013/
- http://www.isuresults.com/results/gpjpn2013/
- http://www.isuresults.com/results/gpf1314/
- http://www.isuresults.com/results/fc2014/
- http://www.isuresults.com/results/ec2014/
- http://www.isuresults.com/results/wjc2014/
- http://www.isuresults.com/results/wc2014/
- http://www.isuresults.com/results/owg2014/

- http://www.isuresults.com/results/jgplat2013/
- http://www.isuresults.com/results/jgpmex2013/
- http://www.isuresults.com/results/jgpsvk2013/
- http://www.isuresults.com/results/jgppol2013/
- http://www.isuresults.com/results/jgpblr2013/
- http://www.isuresults.com/results/jgpcze2013/
- http://www.isuresults.com/results/jgpest2013/

##2014-15
- http://www.isuresults.com/results/gpusa2014/
- http://www.isuresults.com/results/gpcan2014/
- http://www.isuresults.com/results/gpchn2014/
- http://www.isuresults.com/results/gpfra2014/
- http://www.isuresults.com/results/gprus2014/
- http://www.isuresults.com/results/gpjpn2014/
- http://www.isuresults.com/results/gpf1415/
- http://www.isuresults.com/results/fc2015/
- http://www.isuresults.com/results/ec2015/
- http://www.isuresults.com/results/wjc2015/
- http://www.isuresults.com/results/wc2015/

#- junior
- http://www.isuresults.com/results/jgpfra2014/
- http://www.isuresults.com/results/jgpslo2014/
#- http://www.isuresults.com/results/jgpcze2014/
- http://www.isuresults.com/results/jgpjpn2014/
- http://www.isuresults.com/results/jgpest2014/
- http://www.isuresults.com/results/jgpger2014/
- http://www.isuresults.com/results/jgpcro2014/

##2015-16
- http://www.isuresults.com/results/season1516/gpusa2015/
- http://www.isuresults.com/results/season1516/gpcan2015/
- http://www.isuresults.com/results/season1516/gpchn2015/
-
  url: http://www.isuresults.com/results/season1516/gpfra2015/
  comment: "Free Skating has been canceled due to explusion in Paris. refere: http://static.isu.org/media/1012/1980-isu-gp-fra-2015-partial-cancelation-info-to-members-public.pdf"

- http://www.isuresults.com/results/season1516/gprus2015/
- http://www.isuresults.com/results/season1516/gpjpn2015/
- http://www.isuresults.com/results/season1516/gpf1516/
- http://www.isuresults.com/results/season1516/fc2016/
- http://www.isuresults.com/results/season1516/ec2016/
- http://www.isuresults.com/results/season1516/wjc2016/
- http://www.isuresults.com/results/season1516/wc2016/

#- junior
- http://www.isuresults.com/results/season1516/jgpsvk2015/
- http://www.isuresults.com/results/season1516/jgplat2015/
- http://www.isuresults.com/results/season1516/jgpusa2015/
- http://www.isuresults.com/results/season1516/jgpaut2015/
- http://www.isuresults.com/results/season1516/jgppol2015/
- http://www.isuresults.com/results/season1516/jgpesp2015/
- http://www.isuresults.com/results/season1516/jgpcro2015/

##2016-17
- http://www.isuresults.com/results/season1617/gpusa2016/
- http://www.isuresults.com/results/season1617/gpcan2016/
- http://www.isuresults.com/results/season1617/gpchn2016/
- http://www.isuresults.com/results/season1617/gpfra2016/
- http://www.isuresults.com/results/season1617/gprus2016/
- http://www.isuresults.com/results/season1617/gpjpn2016/
- http://www.isuresults.com/results/season1617/gpf1617/
- http://www.isuresults.com/results/season1617/fc2017/
- http://www.isuresults.com/results/season1617/ec2017/
- http://www.isuresults.com/results/season1617/wc2017/
-
  url: http://www.jsfresults.com/intl/2016-2017/wtt/
  parser: :wtt_2017
  comment: "no category results provided"
  
### jnr
- http://www.isuresults.com/results/season1617/jgpfra2016/
- http://www.isuresults.com/results/season1617/jgpcze2016/
- http://www.isuresults.com/results/season1617/jgpjpn2016/
- http://www.isuresults.com/results/season1617/jgprus2016/  ## no country info
- http://www.isuresults.com/results/season1617/jgpslo2016/
- http://www.isuresults.com/results/season1617/jgpest2016/
- http://www.isuresults.com/results/season1617/jgpger2016/
- http://www.isuresults.com/results/season1617/wjc2017/

## for debug
-
  url: http://www.isuresults.com/results/season1516/gpfra2015/
  comment: "Free Skating has been canceled due to explusion in Paris. refere: http://static.isu.org/media/1012/1980-isu-gp-fra-2015-partial-cancelation-info-to-members-public.pdf"
-
  url: http://www.jsfresults.com/intl/2016-2017/wtt/
  parser: :wtt_2017
  comment: "no category results provided"
-
  url: http://www.isuresults.com/results/fc2012/
  parser: :isu_generic_mdy

## ISU-B
- http://www.isuresults.com/results/season1617/wc2017/  

- http://www.deu-event.de/results/Nebelhorn_2016/index.html
- http://www.figureskatingresults.fi/results/1617/CSFIN2016/
- http://www.fisg.it/upload/result/4144/senior/index2.html  # lombardia
- http://www.deu-event.de/results/Nebelhorn_2016/index.html
-
  url: https://skatecanada.ca/event/2016-autumn-classic-international/
  parser: :autumn_classic
- http://www.kraso.sk/wp-content/uploads/sutaze/2016_2017/20160929_mon/

- http://www.isuresults.com/results/season1516/csger2015/  # nebelhorn 2015
- http://www.isuresults.com/results/nt2014/  # nebelhorn 2014
- http://www.deu-event.de/results/Nebelhorn_2012/
- http://www.deu-event.de/results/Nebelhorn_2011/
- http://www.deu-event.de/results/Nebelhorn_2010/
- http://www.isuresults.com/results/nt2013/


-
  url: http://www.isuresults.com/results/fc2012/
  parser: :isu_generic_mdy
-
  url: http://pfsa.com.pl/cspol2016/  # warsaw cup
  attributes:
    country: 'RUS'  
