## Challenger Series

## nebelhorn
- http://www.deu-event.de/results/Nebelhorn_2010/
- http://www.deu-event.de/results/Nebelhorn_2011/
- http://www.deu-event.de/results/Nebelhorn_2012/
- http://www.isuresults.com/results/nt2013/
- http://www.isuresults.com/results/nt2014/
- http://www.isuresults.com/results/season1516/csger2015/
- http://www.deu-event.de/results/Nebelhorn_2016/index.html
- http://www.isuresults.com/results/season1718/csger2017/
  
## finlandia
- http://www.figureskatingresults.fi/results/1718/CSFIN2017/
- http://www.figureskatingresults.fi/results/1617/CSFIN2016/
- http://www.figureskatingresults.fi/results/1516/CSFIN2015/
- http://www.figureskatingresults.fi/results/1415/CSFIN2014/
- http://www.figureskatingresults.fi/results/1314/FT2013/
- http://www.figureskatingresults.fi/results/1213/FT2012/
- http://www.figureskatingresults.fi/results/1112/FT2011/
- http://www.figureskatingresults.fi/results/1011/FT2010/

## lombardia
- http://www.fisg.it/upload/result/4468/index.html
- http://www.fisg.it/upload/result/4144/senior/index2.html
- http://www.fisg.it/upload/result/3860/index.html
- http://www.fisg.it/upload/result/4468/index.html

## ondreij nepela
- http://www.kraso.sk/wp-content/uploads/sutaze/2017_2018/20170921_ont/index.htm
- http://www.kraso.sk/wp-content/uploads/sutaze/2016_2017/20160929_mon/
- http://www.kraso.sk/wp-content/uploads/sutaze/2015_2016/20151001_ont/
#- http://www.kraso.sk/wp-content/uploads/sutaze/2014_2015/20141001_ont/html/
- http://www.kraso.sk/wp-content/uploads/sutaze/2017_2018/20170921_ont/index.htm

## warsaw cup
- http://pfsa.com.pl/cspol2016/  
- http://pfsa.com.pl/cspol15/
- http://www.pfsa.com.pl/warsawcup2014/    
- http://www.pfsa.com.pl/results/1314/WC2013/

## autumn classic
##  this result format is shxt
#-
#  site_url: https://skatecanada.ca/2017-autumn-classic-international/
#  parser_type: autumn_classic
#-
#  site_url: https://skatecanada.ca/event/2016-autumn-classic-international/
#  parser_type: :autumn_classic

## debug
#- http://www.kraso.sk/wp-content/uploads/sutaze/2014_2015/20141001_ont/html/

## 2018-19
#-
#  site_url: https://lamp.skatecanada.ca/results/2018ACI/index.htm
#  parser_type: autumn_classic
