## 2010-11
-
  site_url: http://www.isuresults.com/results/jgpfra2010/
  date_format: "%m/%d/%Y"  
-
  site_url: http://www.isuresults.com/results/jgprou2010/
  date_format: "%m/%d/%Y"  
-
  site_url: http://www.isuresults.com/results/jgpaut2010/
  date_format: "%m/%d/%Y"  
- http://www.isuresults.com/results/jgpjpn2010/
-
  site_url: http://www.isuresults.com/results/jgpgbr2010/
  date_format: "%m/%d/%Y"  
-
  site_url: http://www.isuresults.com/results/jgpger2010/
  date_format: "%m/%d/%Y"  
-
  site_url: http://www.isuresults.com/results/jgpcze2010/
  date_format: "%m/%d/%Y"  
- http://www.isuresults.com/results/wjc2011/

## 2011-12
- http://www.isuresults.com/results/jgplat2011/
- http://www.isuresults.com/results/jgpaus2011/
- http://www.isuresults.com/results/jgppol2011/
- http://www.isuresults.com/results/jgprou2011/
- http://www.isuresults.com/results/jgpaut2011/
- http://www.isuresults.com/results/jgpita2011/
- http://www.isuresults.com/results/jgpest2011/
-
  site_url: http://www.isuresults.com/results/wjc2012/
  date_format: "%m/%d/%Y"  


## 2012-13
- http://www.isuresults.com/results/jgpfra2012/
- http://www.isuresults.com/results/jgpusa2012/
- http://www.isuresults.com/results/jgpaut2012/
- http://www.isuresults.com/results/jgptur2012/
- http://www.isuresults.com/results/jgpslo2012/
- http://www.isuresults.com/results/jgpcro2012/
- http://www.isuresults.com/results/jgpger2012/
- http://www.isuresults.com/results/wjc2013/

## 2013-14
- http://www.isuresults.com/results/jgplat2013/
- http://www.isuresults.com/results/jgpmex2013/
- http://www.isuresults.com/results/jgpsvk2013/
- http://www.isuresults.com/results/jgppol2013/
- http://www.isuresults.com/results/jgpblr2013/
- http://www.isuresults.com/results/jgpcze2013/
- http://www.isuresults.com/results/jgpest2013/
- http://www.isuresults.com/results/wjc2014/

## 2014-15
- http://www.isuresults.com/results/jgpfra2014/
- http://www.isuresults.com/results/jgpslo2014/
- http://www.isuresults.com/results/jgpcze2014/
- http://www.isuresults.com/results/jgpjpn2014/
- http://www.isuresults.com/results/jgpest2014/
- http://www.isuresults.com/results/jgpger2014/
- http://www.isuresults.com/results/jgpcro2014/
- http://www.isuresults.com/results/wjc2015/

## 2015-16
- http://www.isuresults.com/results/season1516/jgpsvk2015/
- http://www.isuresults.com/results/season1516/jgplat2015/
- http://www.isuresults.com/results/season1516/jgpusa2015/
- http://www.isuresults.com/results/season1516/jgpaut2015/
- http://www.isuresults.com/results/season1516/jgppol2015/
- http://www.isuresults.com/results/season1516/jgpesp2015/
- http://www.isuresults.com/results/season1516/jgpcro2015/
- http://www.isuresults.com/results/season1516/wjc2016/

## 2016-17
- http://www.isuresults.com/results/season1617/jgpfra2016/
- http://www.isuresults.com/results/season1617/jgpcze2016/
- http://www.isuresults.com/results/season1617/jgpjpn2016/
- http://www.isuresults.com/results/season1617/jgprus2016/
- http://www.isuresults.com/results/season1617/jgpslo2016/
- http://www.isuresults.com/results/season1617/jgpest2016/
- http://www.isuresults.com/results/season1617/jgpger2016/
- http://www.isuresults.com/results/season1617/wjc2017/

## 2017-18
- http://www.isuresults.com/results/season1718/jgpaus2017/
- http://www.isuresults.com/results/season1718/jgpaut2017/
-
  site_url: http://www.isuresults.com/results/season1718/jgplat2017/
  date_format: "%m/%d/%Y"
- http://www.isuresults.com/results/season1718/jgpblr2017/
-
  site_url: http://www.isuresults.com/results/season1718/jgpcro2017/
  date_format: "%m/%d/%Y"
- http://www.isuresults.com/results/season1718/jgppol2017/
-
  site_url: http://www.isuresults.com/results/season1718/jgpita2017/
  date_format: "%m/%d/%Y" 
 
## 2018-19
-
  site_url: http://www.isuresults.com/results/season1819/jgpaut2018/
  date_format: "%d/%m/%y"
-
  site_url: http://www.isuresults.com/results/season1819/jgpsvk2018/
  date_format: "%d/%m/%Y"
- http://www.isuresults.com/results/season1819/jgpaut2018/
- http://www.isuresults.com/results/season1819/jgpltu2018/
-
  site_url: http://www.isuresults.com/results/season1819/jgpcan2018/
  date_format: "%d/%m/%Y"
- http://www.isuresults.com/results/season1819/jgpcze2018/

## debug
#- http://www.isuresults.com/results/jgpmex2013/     # ladies short judges no3 absence
#- http://www.isuresults.com/results/jgpjpn2010/
