owg: "Olympic Winter Games %{city} %{year}"
wc: "ISU World Championships %{year}"
fcc: ISU Four Continents Championships %{year}
ec: ISU European Championships %{year}
wtt: ISU World Team Trophy %{year}

fin: Finlandia Trophy %{year}
warsaw: Warsaw Cup %{year}
nebelhorn: Nebelhorn Trophy %{year}
lombardia: Lombardia Trophy %{year}
nepela: Ondrej Nepela Trophy %{year}
asianopen: Asian Open %{year}
