## defaults
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

sqlite3_default: &sqlite3_default
  <<: *default
  adapter: sqlite3

postgresql_default: &postgresql_default
  <<: *default
  adapter: postgresql
  username: fisk8viewer
  database: fisk8viewer
  port: 5432  

################
test:
  <<: *sqlite3_default
  database: db/test.sqlite3

################
development_sqlite3: &development_sqlite3
  <<: *sqlite3_default
  database: db/development.sqlite3

development_postgresql: &development_postgresql
  <<: *postgresql_default
  password: fisk8viewer
  host: localhost
  
development:
  <<: *development_sqlite3
#  <<: *development_postgresql

################
production_sqlite3: &production_sqlite3
  <<: *sqlite3_default
  database: db/production.sqlite3

production_postgresql: &production_postgresql
  <<: *postgresql_default
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  #<<: *production_sqlite3
  <<: *production_postgresql
  
