default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

################
development_sqlite3: &development_sqlite3
  <<: *default
  database: db/development.sqlite3

development_postgresql: &development_postgresql
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: fisk8viewer
  database: fisk8viewer
  password: fisk8viewer
  host: localhost
  port: 5432
  
development:
  <<: *development_sqlite3
#  <<: *development_postgresql

################
test:
  <<: *default
  database: db/test.sqlite3

################
production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: fisk8viewer
  database: fisk8viewer
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432

#production:
#  <<: *default
#  database: db/production.sqlite3
  
  
