-
  name: Shin AMANO
  nation: JPN
-
  name: Franca BIANCONI
  nation: ITA
-
  name: Sarkis TEWANIAN
  nation: POL
-
  name: Jae-Eun CHUNG
  nation: KOR
-
  name: Robyn BURLEY
  nation: AUS
-
  name: Leena LAAKSONEN
  nation: FIN
-
  name: Yukiko OKABE
  nation: JPN
-
  name: David SANTEE
  nation: USA
-
  name: Natalia LEBEDEVA
  nation: RUS
-
  name: Hermi OTTEMANN
  nation: NED
-
  name: Masako KAWAI
  nation: JPN
-
  name: Deborah NOYES
  nation: AUZ
-
  name: Evgeny MARTYNOV
  nation: UKR
-
  name: Olga MARKOVA
  nation: RUS
-
  name: Myriam LORIOL-OBERWILER
  nation: SUI
-
  name: Evgeny MARTYNOV
  nation: UKR
-
  name: Fernand FEDRONIC
  nation: FRA
-
  name: Clarence ONG
  nation: AUS
-
  name: Konstantin KOSTIN
  nation: CHE
-
  name: Ricardo OLAVARRIETA
  nation: MEX
-
  name: Olga MARKOVA
  nation: RUS
-
  name: David KIRBY
  nation: USA
-
  name: Ivana JAKUPCEVIC MARINKOVIC,
  nation: CRO
-
  name: Vanessa GUSMEROLI
  nation: SUI                    
