google_analytics:
  tracking_id: <%= ENV['GA_TRACKING_ID'] %>

notification:
  gmail_address: <%= ENV['GMAIL_ADDRESS'] %>
  gmail_password: <%= ENV['GMAIL_PASSWORD'] %>

about:
  name: your name
  mail_address: your@mail.address
  twitter_account: your_twitter_account